### ISSUE TITLE
app.configure

### ISSUE THREAD

**Issue by aric87** [jayzamazing/Restaurant-POS#45]
as far as I know, app.configure is deprecated in Express 4X. should check on that, to make sure that if you update the Express version, it won't break the app.

**Comment by jayzamazing** [comment]
app.configure is more of a feathersjs implementation that anything. So when I do app.configure, it is really doing feathers().configure() instead of express().configure(). "Feathers is another thin abstraction layer over top of Express..." taken from https://docs.feathersjs.com/why/vs/express-socketio.html. So while it is deprecated in express, it is still in use for feathersjs.
